stages:
  - deploy

Deploy:
  only:
    - wip-do-cicd
  stage: deploy
  image: "alpine:latest"
  before_script:
    - apk add --no-cache curl bash zip
  script:
    - /bin/bash ./update.sh
  artifacts:
    paths:
      - log.txt
      - update.zip
    expire_in: 1 hour
    when: always
